[env:esp32dev]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 115200

lib_deps =
  bblanchon/ArduinoJson@^7.0.4
  me-no-dev/ESP Async WebServer@^1.2.3
  me-no-dev/AsyncTCP@^1.1.1

build_flags =
  -D WIFI_SSID=\"${sysenv.MSPA_WIFI_SSID}\"
  -D WIFI_PASSWORD=\"${sysenv.MSPA_WIFI_PASSWORD}\"
  -D API_TOKEN=\"${sysenv.MSPA_API_TOKEN}\"
  -D UART_BAUD=9600
  -D UART_RX_PIN=16
  -D UART_TX_PIN=17
