[env:esp32dev]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 115200

lib_deps =
  bblanchon/ArduinoJson@^7.0.4
  ESP32Async/ESPAsyncWebServer@^3.11.0
  ESP32Async/AsyncTCP@^3.4.10

build_flags =
  -D WIFI_SSID=\"${sysenv.MSPA_WIFI_SSID}\"
  -D WIFI_PASSWORD=\"${sysenv.MSPA_WIFI_PASSWORD}\"
  -D UART_BAUD=9600
  -D UART_RX_PIN=16
  -D UART_TX_PIN=17
